# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.srcs/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1.xci
# IP: The module: 'spi_module_axi_quad_spi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.srcs/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1.xci
# IP: The module: 'spi_module_axi_quad_spi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_module_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
