# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kuszman/Downloads/iis3dwbg1_spi_step6_kr260_hw/kr260_pmod1_spi.xdc

# Block Designs: bd/dma_system/dma_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system || ORIG_REF_NAME==dma_system} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_zynq_ultra_ps_e_0_0/dma_system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==dma_system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_axi_dma_0_0/dma_system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_axi_dma_0_0 || ORIG_REF_NAME==dma_system_axi_dma_0_0} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_axi_smc_1/dma_system_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_axi_smc_1 || ORIG_REF_NAME==dma_system_axi_smc_1} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_rst_ps8_0_99M_1/dma_system_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_rst_ps8_0_99M_1 || ORIG_REF_NAME==dma_system_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_axi_smc_1_0/dma_system_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_axi_smc_1_0 || ORIG_REF_NAME==dma_system_axi_smc_1_0} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_axis_clock_converter_0_0/dma_system_axis_clock_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_axis_clock_converter_0_0 || ORIG_REF_NAME==dma_system_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_xlconstant_0_0/dma_system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_xlconstant_0_0 || ORIG_REF_NAME==dma_system_xlconstant_0_0} -quiet] -quiet

# IP: bd/dma_system/ip/dma_system_ila_0_0/dma_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_system_ila_0_0 || ORIG_REF_NAME==dma_system_ila_0_0} -quiet] -quiet

# XDC: /home/kuszman/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/spi_true/spi_accelerometer_true/spi_accelerometer_true.gen/sources_1/bd/dma_system/dma_system_ooc.xdc
