domain_path: /home/janecki/workspace_vitis/eth_platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/janecki/vitis/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
