#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jul 08 19:25:12 CEST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/janek/${SIM_VER_XSIM}/data"
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_15 -L axi_utils_v2_0_11 -L xbip_pipe_v3_0_11 -L fir_compiler_v7_2_26 -L c_reg_fd_v12_0_11 -L xbip_dsp48_wrapper_v3_0_7 -L c_addsub_v12_0_21 -L mult_gen_v12_0_24 -L cordic_v6_0_25 -L axis_infrastructure_v1_1_1 -L axis_register_slice_v1_1_35 -L axis_subset_converter_v1_1_36 -L c_shift_ram_v12_0_20 -L floating_point_v7_1_21 -L cmpy_v6_0_27 -L xfft_v9_1_15 -L xlconstant_v1_1_10 -L xlslice_v1_0_5 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_top_behav xil_defaultlib.tb_top xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_15 -L axi_utils_v2_0_11 -L xbip_pipe_v3_0_11 -L fir_compiler_v7_2_26 -L c_reg_fd_v12_0_11 -L xbip_dsp48_wrapper_v3_0_7 -L c_addsub_v12_0_21 -L mult_gen_v12_0_24 -L cordic_v6_0_25 -L axis_infrastructure_v1_1_1 -L axis_register_slice_v1_1_35 -L axis_subset_converter_v1_1_36 -L c_shift_ram_v12_0_20 -L floating_point_v7_1_21 -L cmpy_v6_0_27 -L xfft_v9_1_15 -L xlconstant_v1_1_10 -L xlslice_v1_0_5 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_top_behav xil_defaultlib.tb_top xil_defaultlib.glbl -log elaborate.log

