# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kria_kr260.xdc

# Block Designs: bd/spi_module/spi_module.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module || ORIG_REF_NAME==spi_module} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_axi_quad_spi_0_1/spi_module_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_axi_quad_spi_0_1 || ORIG_REF_NAME==spi_module_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_clk_wiz_0/spi_module_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_clk_wiz_0 || ORIG_REF_NAME==spi_module_clk_wiz_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_zynq_ultra_ps_e_0_0/spi_module_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==spi_module_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_axi_smc_0/spi_module_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_axi_smc_0 || ORIG_REF_NAME==spi_module_axi_smc_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_rst_ps8_0_99M_0/spi_module_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_rst_ps8_0_99M_0 || ORIG_REF_NAME==spi_module_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_axi_gpio_0_0/spi_module_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_axi_gpio_0_0 || ORIG_REF_NAME==spi_module_axi_gpio_0_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_axi_dma_0_0/spi_module_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_axi_dma_0_0 || ORIG_REF_NAME==spi_module_axi_dma_0_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_xfft_0_0/spi_module_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_xfft_0_0 || ORIG_REF_NAME==spi_module_xfft_0_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_axi_smc_1_0/spi_module_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_axi_smc_1_0 || ORIG_REF_NAME==spi_module_axi_smc_1_0} -quiet] -quiet

# IP: bd/spi_module/ip/spi_module_axi_smc_2_0/spi_module_axi_smc_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_module_axi_smc_2_0 || ORIG_REF_NAME==spi_module_axi_smc_2_0} -quiet] -quiet

# XDC: /home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/spi/accelerometer_spi/accelerometer_spi.gen/sources_1/bd/spi_module/spi_module_ooc.xdc
