
function tdm_to_parallel_converter_config(this_block)

  % Revision History:
  %
  %   09-Jul-2026  (18:26 hours):
  %     Original code was machine generated by Vitis Model Composer after parsing
  %     C:\Users\janek\AppData\Roaming\Xilinx\Model_Composer\tdm_to_parallel_converter.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('tdm_to_parallel_converter');

  % Vitis Model Composer has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('clk');
  this_block.addSimulinkInport('rst_n');
  this_block.addSimulinkInport('s_axis_tdata');
  this_block.addSimulinkInport('s_axis_tvalid');
  this_block.addSimulinkInport('s_axis_tlast');
  this_block.addSimulinkInport('m_axis_tready');

  this_block.addSimulinkOutport('s_axis_tready');
  this_block.addSimulinkOutport('m_axis_tdata');
  this_block.addSimulinkOutport('m_axis_tvalid');
  this_block.addSimulinkOutport('m_axis_tlast');

  s_axis_tready_port = this_block.port('s_axis_tready');
  s_axis_tready_port.setType('UFix_1_0');
  s_axis_tready_port.useHDLVector(false);

  m_axis_tdata_port = this_block.port('m_axis_tdata');
  m_axis_tdata_port.setType('UFix_96_0');

  m_axis_tvalid_port = this_block.port('m_axis_tvalid');
  m_axis_tvalid_port.setType('UFix_1_0');
  m_axis_tvalid_port.useHDLVector(false);

  m_axis_tlast_port = this_block.port('m_axis_tlast');
  m_axis_tlast_port.setType('UFix_1_0');
  m_axis_tlast_port.useHDLVector(false);


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('clk').width ~= 1)
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

    if (this_block.port('rst_n').width ~= 1)
      this_block.setError('Input data type for port "rst_n" must have width=1.');
    end

    this_block.port('rst_n').useHDLVector(false);

    if (this_block.port('s_axis_tdata').width ~= 32)
      this_block.setError('Input data type for port "s_axis_tdata" must have width=32.');
    end

    if (this_block.port('s_axis_tvalid').width ~= 1)
      this_block.setError('Input data type for port "s_axis_tvalid" must have width=1.');
    end

    this_block.port('s_axis_tvalid').useHDLVector(false);

    if (this_block.port('s_axis_tlast').width ~= 1)
      this_block.setError('Input data type for port "s_axis_tlast" must have width=1.');
    end

    this_block.port('s_axis_tlast').useHDLVector(false);

    if (this_block.port('m_axis_tready').width ~= 1)
      this_block.setError('Input data type for port "m_axis_tready" must have width=1.');
    end

    this_block.port('m_axis_tready').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % Vitis Model Composer found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('tdm_to_parallel_converter.v');

return;


% This function converts the matlab array to VHDL array Style 
% and this is valid only in case of generic parameters. 
function arrayHDLType = convertArrayType(inArr) 
arrayHDLType = '';
for i=1:length(inArr)
    if (i == 1)
        arrayHDLType = [arrayHDLType '(' num2str(inArr(i))]; 
    elseif (i == length(inArr)) 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i)) ')']; 
    else 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i))]; 
    end 
end 
