#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Script generated by Vivado on Wed Jul 08 19:25:07 CEST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : Hilbert_fft.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : Hilbert_fft.sh
#                Hilbert_fft.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                Hilbert_fft.sh [-rerun]
#                Hilbert_fft.sh [-reset_run]
#                Hilbert_fft.sh [-clean]
#                Hilbert_fft.sh [-reset_log]
#                Hilbert_fft.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'Hilbert_fft.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************
export SIM_VER_VCS=
export GCC_VER_VCS=

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xbip_utils_v3_0_15 axi_utils_v2_0_11 xbip_pipe_v3_0_11 fir_compiler_v7_2_26 xil_defaultlib c_reg_fd_v12_0_11 xbip_dsp48_wrapper_v3_0_7 c_addsub_v12_0_21 mult_gen_v12_0_24 cordic_v6_0_25 axis_infrastructure_v1_1_1 axis_register_slice_v1_1_35 axis_subset_converter_v1_1_36 c_shift_ram_v12_0_20 floating_point_v7_1_21 cmpy_v6_0_27 xfft_v9_1_15 xlconstant_v1_1_10 xlslice_v1_0_5)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "Hilbert_fft.sh - Script generated by export_simulation (Vivado v2025.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./Hilbert_fft.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vhdlan -work xbip_utils_v3_0_15 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/fb6f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vhdlan -work axi_utils_v2_0_11 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/c6be/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_pipe_v3_0_11 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/6a79/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work fir_compiler_v7_2_26 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/655f/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_fir_compiler_0_0/sim/Hilbert_fft_fir_compiler_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_reg_fd_v12_0_11 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/0ff7/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_dsp48_wrapper_v3_0_7 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/9bc6/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_addsub_v12_0_21 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/ed70/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work mult_gen_v12_0_24 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/6d7a/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work cordic_v6_0_25 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/32c3/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_cordic_0_0/sim/Hilbert_fft_cordic_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axis_infrastructure_v1_1_1 $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work axis_register_slice_v1_1_35 $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/be12/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tdata_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tuser_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tstrb_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tkeep_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tid_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tdest_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/tlast_Hilbert_fft_axis_subset_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axis_subset_converter_v1_1_36 $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/5e96/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/hdl/top_Hilbert_fft_axis_subset_converter_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_0_0/sim/Hilbert_fft_axis_subset_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work c_shift_ram_v12_0_20 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/89b5/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work floating_point_v7_1_21 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/c90d/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work cmpy_v6_0_27 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/c96a/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xfft_v9_1_15 $vhdlan_opts -vhdl08 \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/5ee3/hdl/xfft_v9_1_vh08_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xfft_v9_1_15 $vhdlan_opts \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/5ee3/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_xfft_0_0/sim/Hilbert_fft_xfft_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_TDM_to_Parallel_Conv_0_0/sim/Hilbert_fft_TDM_to_Parallel_Conv_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_10 $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_xlconstant_0_0/sim/Hilbert_fft_xlconstant_0_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_xlconstant_1_0/sim/Hilbert_fft_xlconstant_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_brancher_0_0/sim/Hilbert_fft_brancher_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_cordic_1_3/sim/Hilbert_fft_cordic_1_3.vhd" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_cordic_1_4/sim/Hilbert_fft_cordic_1_4.vhd" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_cordic_1_5/sim/Hilbert_fft_cordic_1_5.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_fir0_spy_0_2/sim/Hilbert_fft_fir0_spy_0_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_fir_compiler_1_0/sim/Hilbert_fft_fir_compiler_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xlslice_v1_0_5 $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/6792/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../Hilbert_and_fft_test.gen/sources_1/bd/Hilbert_fft/ipshared/434f/hdl" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_xlslice_1_0/sim/Hilbert_fft_xlslice_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_xlslice_1_1/sim/Hilbert_fft_xlslice_1_1.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_fir0_spy_1_0/sim/Hilbert_fft_fir0_spy_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_fir0_spy_1_1/sim/Hilbert_fft_fir0_spy_1_1.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tdata_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tuser_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tstrb_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tkeep_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tid_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tdest_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/tlast_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/hdl/top_Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/ip/Hilbert_fft_axis_subset_converter_1_0/sim/Hilbert_fft_axis_subset_converter_1_0.v" \
  "../../../bd/Hilbert_fft/sim/Hilbert_fft.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Hilbert_fft xil_defaultlib.glbl -o Hilbert_fft_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Hilbert_fft_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

  # delete previous design library generated data
  if [[ ($b_clean == 1) ]]; then
    clean
    echo -e "INFO: Design library generated data deleted.\n"
    exit 0
  fi

  # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_rerun == 1) ]]; then
    # keep previous state for incremental run
    return 0
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/janek/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/Hilbert_with_fft/Hilbert_and_fft_test/Hilbert_and_fft_test.cache/compile_simlib/vcs"
  fi

  echo "LIBRARY_SCAN=TRUE" >> $file

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Hilbert_fft_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc Hilbert_fft_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated design library data from the previous run
clean()
{
  files_to_remove=("${design_libs[@]}")
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="$sim_lib_dir/${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  # delete design library directory
  rm -rf $sim_lib_dir
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./Hilbert_fft.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -rerun)         b_rerun=1         ;;
      -reset_run)     b_reset_run=1     ;;
      -clean)         b_clean=1         ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -clean is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_clean == 1) ]]; then
    echo -e "ERROR: -clean switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: Hilbert_fft.sh [-help]\n\
Usage: Hilbert_fft.sh [-step]\n\
Usage: Hilbert_fft.sh [-lib_map_path]\n\
Usage: Hilbert_fft.sh [-rerun]\n\
Usage: Hilbert_fft.sh [-reset_run]\n\
Usage: Hilbert_fft.sh [-clean]\n\
Usage: Hilbert_fft.sh [-reset_log]\n\
Usage: Hilbert_fft.sh [-keep_index]\n\
Usage: Hilbert_fft.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-rerun] -- Rerun step(s) in incremental mode (data generated from the previous run will be retained).\n\
To rerun a specific step, pass the -step <name> switch in addition to -rerun switch.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-clean] -- Delete simulator generated design library data from the previous run. This switch will not\n\
execute steps defined in the script.\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_rerun=0
b_reset_run=0
b_clean=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
