# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ethernet/ethernet.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet || ORIG_REF_NAME==ethernet} -quiet] -quiet

# IP: bd/ethernet/ip/ethernet_zynq_ultra_ps_e_0_0/ethernet_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ethernet_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ethernet/ip/ethernet_axi_dma_0_0/ethernet_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet_axi_dma_0_0 || ORIG_REF_NAME==ethernet_axi_dma_0_0} -quiet] -quiet

# IP: bd/ethernet/ip/ethernet_axi_smc_0/ethernet_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet_axi_smc_0 || ORIG_REF_NAME==ethernet_axi_smc_0} -quiet] -quiet

# IP: bd/ethernet/ip/ethernet_rst_ps8_0_99M_0/ethernet_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet_rst_ps8_0_99M_0 || ORIG_REF_NAME==ethernet_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/ethernet/ip/ethernet_axis_test_gen_0_0/ethernet_axis_test_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet_axis_test_gen_0_0 || ORIG_REF_NAME==ethernet_axis_test_gen_0_0} -quiet] -quiet

# IP: bd/ethernet/ip/ethernet_xlconstant_0_0/ethernet_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ethernet_xlconstant_0_0 || ORIG_REF_NAME==ethernet_xlconstant_0_0} -quiet] -quiet

# XDC: /home/kuszman/Magisterka/Intelligent-Vibroacoustic-Machine-Diagnostic-System-on-FPGA/ethernet/project_1/project_1.gen/sources_1/bd/ethernet/ethernet_ooc.xdc
