
function fir_compiler_2_wrapper_config(this_block)

  % Revision History:
  %
  %   06-Aug-2026  (08:23 hours):
  %     Original code was machine generated by Vitis Model Composer after parsing
  %     C:\Users\janek\AppData\Roaming\Xilinx\Model_Composer\fir_compiler_2_wrapper.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('fir_compiler_2_wrapper');

  % Vitis Model Composer has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('s_axis_data_tvalid');
  this_block.addSimulinkInport('s_axis_data_tlast');
  this_block.addSimulinkInport('s_axis_data_tdata');
  this_block.addSimulinkInport('m_axis_data_tready');

  this_block.addSimulinkOutport('s_axis_data_tready');
  this_block.addSimulinkOutport('m_axis_data_tvalid');
  this_block.addSimulinkOutport('m_axis_data_tlast');
  this_block.addSimulinkOutport('m_axis_data_tdata');
  this_block.addSimulinkOutport('event_s_data_tlast_missing');
  this_block.addSimulinkOutport('event_s_data_tlast_unexpected');

  s_axis_data_tready_port = this_block.port('s_axis_data_tready');
  s_axis_data_tready_port.setType('UFix_1_0');
  s_axis_data_tready_port.useHDLVector(false);

  m_axis_data_tvalid_port = this_block.port('m_axis_data_tvalid');
  m_axis_data_tvalid_port.setType('UFix_1_0');
  m_axis_data_tvalid_port.useHDLVector(false);

  m_axis_data_tlast_port = this_block.port('m_axis_data_tlast');
  m_axis_data_tlast_port.setType('UFix_1_0');
  m_axis_data_tlast_port.useHDLVector(false);

  m_axis_data_tdata_port = this_block.port('m_axis_data_tdata');
  m_axis_data_tdata_port.setType('Fix_16_10');

  event_s_data_tlast_missing_port = this_block.port('event_s_data_tlast_missing');
  event_s_data_tlast_missing_port.setType('UFix_1_0');
  event_s_data_tlast_missing_port.useHDLVector(false);

  event_s_data_tlast_unexpected_port = this_block.port('event_s_data_tlast_unexpected');
  event_s_data_tlast_unexpected_port.setType('UFix_1_0');
  event_s_data_tlast_unexpected_port.useHDLVector(false);


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('s_axis_data_tvalid').width ~= 1)
      this_block.setError('Input data type for port "s_axis_data_tvalid" must have width=1.');
    end

    this_block.port('s_axis_data_tvalid').useHDLVector(false);

    if (this_block.port('s_axis_data_tlast').width ~= 1)
      this_block.setError('Input data type for port "s_axis_data_tlast" must have width=1.');
    end

    this_block.port('s_axis_data_tlast').useHDLVector(false);

    if (this_block.port('s_axis_data_tdata').width ~= 16)
      this_block.setError('Input data type for port "s_axis_data_tdata" must have width=16.');
    end

    if (this_block.port('m_axis_data_tready').width ~= 1)
      this_block.setError('Input data type for port "m_axis_data_tready" must have width=1.');
    end

    this_block.port('m_axis_data_tready').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('fir_compiler_2_wrapper.v');
  this_block.addFile('fir_compiler_2.xci');
  this_block.addFile('fir_compiler_2_sim_netlist.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 && uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

% This function converts the matlab array to VHDL array Style 
% and this is valid only in case of generic parameters. 
function arrayHDLType = convertArrayType(inArr) 
arrayHDLType = '';
for i=1:length(inArr)
    if (i == 1)
        arrayHDLType = [arrayHDLType '(' num2str(inArr(i))]; 
    elseif (i == length(inArr)) 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i)) ')']; 
    else 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i))]; 
    end 
end 
