set_property SRC_FILE_INFO {cfile:/home/kuszman/Downloads/iis3dwbg1_spi_step6_kr260_hw/kr260_pmod1_spi.xdc rfile:../../../../../../../../Downloads/iis3dwbg1_spi_step6_kr260_hw/kr260_pmod1_spi.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports clk_25mhz]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports spi_cs_n]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports spi_sclk]
